SET(SDL2_ttf_SEARCH_PATHS
	~/Library/Frameworks
	/Library/Frameworks
	/usr/local
	/usr
	/sw # Fink
	/opt/local # DarwinPorts
	/opt/csw # Blastwave
	/opt
	${SDL2_ttf_PATH}
)

FIND_PATH(SDL2_ttf_INCLUDE_DIR SDL_ttf.h
	HINTS
	$ENV{SDL2_ttfDIR}
	PATH_SUFFIXES include
	PATHS ${SDL2_ttf_SEARCH_PATHS}
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8) 
	set(PATH_SUFFIXES lib64 lib/x64 lib)
else() 
	set(PATH_SUFFIXES lib/x86 lib)
endif() 

FIND_LIBRARY(SDL2_ttf_LIBRARY_TEMP
	NAMES SDL2_ttf
	HINTS
	$ENV{SDL2_ttfDIR}
	PATH_SUFFIXES ${PATH_SUFFIXES}
	PATHS ${SDL2_ttf_SEARCH_PATHS}
)

IF(NOT SDL2_ttf_BUILDING_LIBRARY)
	IF(NOT ${SDL2_ttf_INCLUDE_DIR} MATCHES ".framework")
		FIND_LIBRARY(SDL2_ttfMAIN_LIBRARY
			NAMES SDL2_ttfmain
			HINTS
			$ENV{SDL2_ttfDIR}
			PATH_SUFFIXES ${PATH_SUFFIXES}
			PATHS ${SDL2_ttf_SEARCH_PATHS}
		)
	ENDIF(NOT ${SDL2_ttf_INCLUDE_DIR} MATCHES ".framework")
ENDIF(NOT SDL2_ttf_BUILDING_LIBRARY)

IF(NOT APPLE)
	FIND_PACKAGE(Threads)
ENDIF(NOT APPLE)

IF(MINGW)
	SET(MINGW32_LIBRARY mingw32 "-mwindows" CACHE STRING "mwindows for MinGW")
ENDIF(MINGW)

IF(SDL2_ttf_LIBRARY_TEMP)
	IF(NOT SDL2_ttf_BUILDING_LIBRARY)
		IF(SDL2_ttfMAIN_LIBRARY)
			SET(SDL2_ttf_LIBRARY_TEMP ${SDL2_ttfMAIN_LIBRARY} ${SDL2_ttf_LIBRARY_TEMP})
		ENDIF(SDL2_ttfMAIN_LIBRARY)
	ENDIF(NOT SDL2_ttf_BUILDING_LIBRARY)

	IF(APPLE)
		SET(SDL2_ttf_LIBRARY_TEMP ${SDL2_ttf_LIBRARY_TEMP} "-framework Cocoa")
	ENDIF(APPLE)

	IF(NOT APPLE)
		SET(SDL2_ttf_LIBRARY_TEMP ${SDL2_ttf_LIBRARY_TEMP} ${CMAKE_THREAD_LIBS_INIT})
	ENDIF(NOT APPLE)

	IF(MINGW)
		SET(SDL2_ttf_LIBRARY_TEMP ${MINGW32_LIBRARY} ${SDL2_ttf_LIBRARY_TEMP})
	ENDIF(MINGW)

	SET(SDL2_ttf_LIBRARY ${SDL2_ttf_LIBRARY_TEMP} CACHE STRING "Where the SDL2_ttf Library can be found")
	SET(SDL2_ttf_LIBRARY_TEMP "${SDL2_ttf_LIBRARY_TEMP}" CACHE INTERNAL "")
ENDIF(SDL2_ttf_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_ttf_LIBRARY SDL2_ttf_INCLUDE_DIR)